# Generated by Django 2.2.2 on 2019-06-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorboard', '0002_tuteecomment_tutorcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuteecomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuteeComments', to='tutorboard.TutorApply'),
        ),
        migrations.AlterField(
            model_name='tutorcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorComments', to='tutorboard.TutorRequest'),
        ),
    ]
